

https://www.sheffield.ac.uk/mash/statistics/datasets

In [1]:


#importing the required packes for  use in the study.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.stats import ttest_rel
import pingouin as pg

# here I am removing a nuicence error related to calculation of values using arrays.
pd.options.mode.chained_assignment = None

# setting the graph size
plt.rcParams["figure.figsize"] =(10,6)

In [2]:
# eyball the data
df = pd.read_csv('data/videodata.csv')
df.head()

,Person,Gender,Heardofcondition,Set,@1st,@2nd,@3rd,@4th,Combination,VideoAGenUnderstandingCONDITION,VideoBdoctorUnderstandingCONDITION,VideoCOldUnderstandingCONDITION,DEMOUnderstandingCONDITION,TotalAGen,TotalBdoc,TotalCOld,TotalDDEMO
0,1,1,1,1,4,1,3,2,4132,5,5,3,5,25,23,13,22
1,2,2,1,1,4,1,3,2,4132,5,5,5,5,23,23,20,22
2,3,2,2,1,4,1,3,2,4132,4,4,2,5,20,17,14,23
3,4,2,0,1,4,1,3,2,4132,5,5,5,5,24,24,23,25
4,5,2,2,1,4,1,3,2,4132,5,5,4,5,25,22,18,23